#include "lcd.h"
#include "chunk.h"

#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_START_X_CHUNK    0
#define CONFIG_START_Y_CHUNK    0

#define CONFIG_START_X_TL       10
#define CONFIG_START_Y_TL       10

#define CONFIG_DEQUE_MAX_SIZE   8
#define CONFIG_DDEQUE_MAX_SIZE  CONFIG_DEQUE_MAX_SIZE

#define CONFIG_D2DEQUE_MAX_ROWS 12
#define CONFIG_D2DEQUE_MAX_COLS 12

#define CONFIG_COLOR_DESERT     rgb565(186, 128, 15)
#define CONFIG_COLOR_CACTUS     rgb565(0, 200, 0)

#define CONFIG_TEXT_SIZE        2
#define CONFIG_CHAR_W           (CONFIG_TEXT_SIZE*LCD_CHAR_W)
#define CONFIG_CHAR_H           (CONFIG_TEXT_SIZE*LCD_CHAR_H)
#define CONFIG_CHUNK_W          (CONFIG_CHAR_W*CHUNK_TILE_COLS)
#define CONFIG_CHUNK_H          (CONFIG_CHAR_H*CHUNK_TILE_ROWS)

#define CONFIG_CACTUS_LEVEL     10
#define CONFIG_CACTUS_INCREMENT 10

#define CONFIG_STEP_SIZE        2

#define CONFIG_JOY_INPUT_BUFFER 1500
#define CONFIG_JOY_NUM_SAMPLES  10

#define CONFIG_SCREEN_CULLING_BUFFER_SIZE 20
#define CONFIG_POSITION_BUFFER_SIZE 20

#define CONFIG_PLAYER_WIDTH     (CONFIG_CHAR_W-2)
#define CONFIG_PLAYER_HEIGHT    (CONFIG_CHAR_H-2)
#define CONFIG_PLAYER_LEFT_BOUND    ((LCD_W-CONFIG_PLAYER_WIDTH)/2)
#define CONFIG_PLAYER_RIGHT_BOUND   ((LCD_W+CONFIG_PLAYER_WIDTH)/2)
#define CONFIG_PLAYER_UP_BOUND      ((LCD_H-CONFIG_PLAYER_HEIGHT)/2)
#define CONFIG_PLAYER_DOWN_BOUND    ((LCD_H+CONFIG_PLAYER_HEIGHT)/2)

#define CONFIG_PLAYER_COLOR     MAGENTA







#endif // CONFIG_H